name = "pastel-poker-planning"
compatibility_date = "2024-01-01"

[env.production]
name = "pastel-poker-planning"

[env.preview]
name = "pastel-poker-planning-preview"

# Build configuration for Cloudflare Pages
pages_build_output_dir = "dist"
